language: node_js
node_js: '6'
deploy:
  provider: npm
  email: felix@stkn.org
  api_key:
    secure: XqW2S2mkTS9oP77HjO1Ui9TgXI1s4I+1YPrG7gPG1o6qBU59ZRGEEidDgkFi//m7sDF9Oo+Xp5r1EC9Ij3ztQ+1kMDwz9aa2Bt2uOanqRpKy9AUKo6Y66exolZ8WZVnVfGaa2eKo5UAzrg+7EDYFZpDhZyWeYYd9PWiJfUjOArup4bNEpQmPz9RyTFGe0P6rj0dAeSgmBaaMadROAr2c7G09CHGH7CctTXH5NTz6HPBcsqxMOqQ2vMJwkid+cdJWWnL8zGUsmGvuGI/4VVnVo+n9gydtz3wvYHQjLVUHCz3yMd5A1YMWxdBe017jELluVm6Ko1imdv1qclZbpOb3qSCDqkfyxvrCF5WudVT4thggS6PTIOpzwuhm71/kX/aoKehDwm20oNsLMY5Ig+z3TpUC7rBduCYaGXfNIuSOHXMJtSTWhbTWvxpTdIKfyYZt5UcgChyrx8gjQ1yJyGpqq/kPOynJ9mu581/nwuKNl+Axx5+tHKD+fB27hxFwYJK+jE/23nwkPXsxsk91cuZvlYiFY7n3jFbtQQ9LoJb88Af0fkiQQ4P9ja5V3TdSP3j1XYuXvt1/P/23o5VnVLLriesQMUb3l9izgce11d5lBie8pwWa9KxiE4zJ6YNg4V+rdiknkEq7FgqqJmyqnjN10Onkoe07y00QlJsj95VkpMk=
  on:
    tags: true
    repo: cebor/rollup-plugin-angular
